# Generated by Django 4.2.7 on 2023-12-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_rename_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image',
        ),
    ]
